# Beginner tutorial on PyTorch and ANN - Artificial Neural Network - Feedforward / Fully-Connected

In [1]:
import torch

In [2]:
torch.__version__

'2.1.0'

In [4]:
#deep learning can use CPU or GPU
torch.cuda.is_available()

False

In [6]:
device = torch.device('cpu') #torch.device('cuda0')
device

device(type='cpu')

## Let's start

<img src = '../figures/japan.png'>

In [ ]:
'''
m = 5
n = 3 --> temp, rain, hum
y = yield of apples, and oranges
'''

## 1. Specify X and Y

In [8]:
import numpy as np
# Input (temp, rainfall, humidity)
X_train = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
Y_train = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')


In [12]:
#have to convert numpy to torch tensors
#torch tensors are simply numpy version of pytorch
inputs  = torch.from_numpy(X_train)
targets = torch.from_numpy(Y_train)

type(inputs), type(targets) #torch.Tensor

#same thing
inputs.shape, targets.shape
inputs.size(), targets.size()

(torch.Size([15, 3]), torch.Size([15, 2]))

## 2. Dataloaders

Remember in ML, we have to do the batch learning outselve, like mini-batch, stochastic batch.  PyTorch has a class called `DataLoaders` that automatically do this for you.

It's optional whether you wanna use it, or just use it - don't reinvent the wheel

In [16]:
#define a dataset so that dataloaders understand
from torch.utils.data import TensorDataset

train_dataset = TensorDataset(inputs, targets)

train_dataset[0]

(tensor([73., 67., 43.]), tensor([56., 70.]))

In [19]:
from torch.utils.data import DataLoader

batch_size = 3  #for no reason - here i am using a mini-batch of size 3
train_dl   = DataLoader(train_dataset, batch_size, shuffle=False, num_workers=4) #you should use Shuffle=True

In [20]:
for x, y in train_dl:
    print("------new batch------")
    print(x)  #this will give you "batch_size" of x, e.g., 3 sets of x
    print(y)  #this will give you "batch size" of y, e.g., 3 sets of y

------new batch------
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]])
------new batch------
tensor([[102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.]])
tensor([[ 22.,  37.],
        [103., 119.],
        [ 56.,  70.]])
------new batch------
tensor([[ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.]])
tensor([[ 81., 101.],
        [119., 133.],
        [ 22.,  37.]])
------new batch------
tensor([[69., 96., 70.],
        [73., 67., 43.],
        [91., 88., 64.]])
tensor([[103., 119.],
        [ 56.,  70.],
        [ 81., 101.]])
------new batch------
tensor([[ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[119., 133.],
        [ 22.,  37.],
        [103., 119.]])
