# Beginner tutorial on PyTorch and ANN - Artificial Neural Network - Feedforward / Fully-Connected

In [1]:
import torch

In [2]:
torch.__version__

'2.1.0'

In [4]:
#deep learning can use CPU or GPU
#pip install cuda..something - search online
torch.cuda.is_available()

False

In [6]:
device = torch.device('cpu') #torch.device('cuda0')
device

device(type='cpu')

## Let's start

<img src = '../figures/japan.png'>

In [ ]:
'''
m = 5
n = 3 --> temp, rain, hum
y = yield of apples, and oranges
'''

## 1. Specify X and Y

In [8]:
import numpy as np
# Input (temp, rainfall, humidity)
X_train = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
Y_train = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')


In [12]:
#have to convert numpy to torch tensors
#torch tensors are simply numpy version of pytorch
inputs  = torch.from_numpy(X_train)
targets = torch.from_numpy(Y_train)

type(inputs), type(targets) #torch.Tensor

#same thing
inputs.shape, targets.shape
inputs.size(), targets.size()

(torch.Size([15, 3]), torch.Size([15, 2]))

## 2. Dataloaders

Remember in ML, we have to do the batch learning outselve, like mini-batch, stochastic batch.  PyTorch has a class called `DataLoaders` that automatically do this for you.

It's optional whether you wanna use it, or just use it - don't reinvent the wheel

In [16]:
#define a dataset so that dataloaders understand
from torch.utils.data import TensorDataset

train_dataset = TensorDataset(inputs, targets)

train_dataset[0]

(tensor([73., 67., 43.]), tensor([56., 70.]))

In [19]:
from torch.utils.data import DataLoader

batch_size = 3  #for no reason - here i am using a mini-batch of size 3
train_dl   = DataLoader(train_dataset, batch_size, shuffle=False, num_workers=4) #you should use Shuffle=True

In [20]:
for x, y in train_dl:
    print("------new batch------")
    print(x)  #this will give you "batch_size" of x, e.g., 3 sets of x
    print(y)  #this will give you "batch size" of y, e.g., 3 sets of y

------new batch------
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]])
------new batch------
tensor([[102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.]])
tensor([[ 22.,  37.],
        [103., 119.],
        [ 56.,  70.]])
------new batch------
tensor([[ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.]])
tensor([[ 81., 101.],
        [119., 133.],
        [ 22.,  37.]])
------new batch------
tensor([[69., 96., 70.],
        [73., 67., 43.],
        [91., 88., 64.]])
tensor([[103., 119.],
        [ 56.,  70.],
        [ 81., 101.]])
------new batch------
tensor([[ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## 3. Define some layers!!!

Don't be confused about "layer", it's simply matrix multiplication.  It's true until now...

In [22]:
import torch.nn as nn #nn ==> neural network

In [23]:
some_random_layer = nn.Linear(3, 2)  #(3 = incoming features, 2 = output features)

In [26]:
print(some_random_layer.weight)  # matrix --> randomly initialize --> using standardization methods
print(some_random_layer.weight.shape)
print(some_random_layer.bias)
print(some_random_layer.bias.shape)

Parameter containing:
tensor([[ 0.2159,  0.0441, -0.1519],
        [-0.1534, -0.0395, -0.2908]], requires_grad=True)
torch.Size([2, 3])
Parameter containing:
tensor([0.4727, 0.5361], requires_grad=True)
torch.Size([2])


In [28]:
outputs = some_random_layer(inputs)
#inputs = (15, 3)  @ (3, 2) = (15, 2)
outputs.shape

torch.Size([15, 2])

In [34]:
#how do chatgpt count their number of parameters - 175b parameters
total_num_of_params = 0
for param in some_random_layer.parameters():
    total_num_of_params += param.numel()
    
print(total_num_of_params)

8


## 4. Define loss function

In [38]:
#recall that this is a regression problem
#so we have to use MSE
#you can code it by yourself - or you can use built-in pytorch module
criterion = nn.MSELoss()

In [39]:
mse = criterion(targets, outputs)

In [41]:
print(mse.item())

10938.7158203125


## 5. Define our gradient descent algorithm