# Linear Regression using Sklearn

[Scikit-Learn](http://scikit-learn.org) provides quick access to a huge pool of machine learning algorithms.

Before using sklearn, there is **one thing you need to know**, i.e., the **data shape that sklearn wants**.

To apply majority of the algorithms, sklearn requires two inputs, i.e., $\mathbf{X}$ and $\mathbf{y}$.

-  $\mathbf{X}$, or the **feature matrix** *typically* has the shape of ``[n_samples, n_features]``
-  $\mathbf{y}$, or the **target/label vector** *typically* has the shape of ``[n_samples, ]`` or ``[n_samples, n_targets]`` depending whether that algorithm supports multiple labels

<img src = "figures/shape.png">

Note 1:  if you $\mathbf{X}$ has only 1 feature, the shape must be ``[n_samples, 1]`` NOT ``[n_samples, ]``

Note 2:  sklearn supports both numpy and pandas, as long as the shape is right.  For example, if you use pandas, $\mathbf{X}$ would be a dataframe, and $\mathbf{y}$ could be a series or dataframe.

Tips:  it's always better to look at sklearn documentation before applying any algorithm.

## Basics of the sklearn API

Most commonly, the steps in using the Scikit-Learn API are as follows:

1. Import a class of model
2. Choose model hyperparameters by instantiating this class with desired values.
3. Arrange data into a features matrix and target vector following the discussion above.
4. Fit the model to your data by calling the ``fit()`` method of the model instance.
5. Perform inference using the ``predict()`` method.

## Let's try!

Before anything, let's load a toy regression dataset.

In [1]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## 1. Import a class of model

In [2]:
from sklearn.linear_model import LinearRegression

## 2. Choose model hyperparameters

For our linear regression example, we can instantiate the ``LinearRegression`` class and specify that we would like to fit the intercept using the ``fit_intercept`` hyperparameter:

In [3]:
model = LinearRegression(fit_intercept=True)
model

LinearRegression()

## 3. Arrange data into a features matrix and target vector

In [4]:
assert len(X_train.shape) == 2 and len(X_test.shape) == 2  #correct shape!

In [5]:
assert len(y_train.shape) == 1 and len(y_test.shape) == 1  #correct shape!

## 4. Fit the model to your data

In [6]:
model.fit(X_train, y_train)  #when you train your model, use your training set

LinearRegression()

This ``fit()`` command causes a number of model-dependent internal computations to take place, and the results of these computations are stored in model-specific attributes that the user can explore.
In Scikit-Learn, by convention all model parameters that were learned during the ``fit()`` process have trailing underscores; for example in this linear model, we have the following:

In [7]:
model.coef_

array([ -0.87547741,  -9.26843436,  23.24283857,  18.52697371,
       -30.72400693,  17.48415588,   2.06334652,   7.45377418,
        33.45802239,   2.61129274])

In [8]:
model.intercept_

151.29126213592232

These two parameters represent the slope and intercept of the simple linear fit to the data.

## 5. Predict labels for unknown data

Once the model is trained, we can now evaluate our model which is called **inference** or **testing**.  Usually we do this with test set (but here we are just lazy for simplicity).  

In Scikit-Learn, this can be done using the ``predict()`` method.
For the sake of this example, our "new data" will be a grid of *x* values, and we will ask what *y* values the model predicts:

In [9]:
y_hat = model.predict(X_test)  #inference

In [10]:
# compute mean squared error

from sklearn.metrics import mean_squared_error

# mean_squared_error(y_true, y_pred)
mean_squared_error(y_test, y_hat)

3180.1621027594665

As you can see, it's very close to what we got before, using our code from scratch, but with 10x fewer lines :-)!

## Cross-validation

Having only two sets, i.e., training and test set is NOT recommended because:

1. What if I want to check which hyperparameter is good?  How to check when I should NEVER touch test set?

2. What if somehow I got lucky with my split and my training set is very good, and my test set is also very good, just **by chance*?
 
The recommended way is to do **cross-validation**

- **Idea**:  further **split the training set into actual training set and validation set**.  To make sure we don't get lucky with our validation set, we do this split either randomly or walkforward like in this picture:

<img width="400" src = "figures/cv.png" >

Here we split the data into five groups, and use each of them in turn to evaluate the model fit on the other 4/5 of the data.  This would be rather tedious to do by hand, and so we can use Scikit-Learn's ``cross_val_score`` convenience routine to do it succinctly

In [11]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, X_train, y_train, cv=5) 

array([0.21229232, 0.45349073, 0.51633375, 0.58399592, 0.64328844])

By default, if we specify cv with integer, the <code>cross_val_score</code> uses KFold strategies by default (KFold is basically the picture above).  We can also manually specify the CV strategies we want.

<img width="400" src = "figures/kfold.png">

For example, **ShuffleSplit**:

ShuffleSplit is a good alternative to KFold cross validation that allows a finer control on the number of iterations and the proportion of samples on each side of the train / test split.

<img width="400" src = "figures/shuffle.png">

In [12]:
from sklearn.model_selection import ShuffleSplit

shuffle_cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)  #splitting in a randomized way
cross_val_score(model, X_train, y_train, cv=shuffle_cv) 

array([0.55653483, 0.61272515, 0.49418558, 0.2213325 , 0.40555013])

Another common strategy is **Stratified KFold**

StratifiedKFold is a variation of k-fold which returns stratified folds: **each set contains approximately the same percentage of samples of each target class**.

<img width="400" src = "figures/skfold.png">

In [13]:
from sklearn.model_selection import StratifiedKFold #mostly used for classification

sk_cv = StratifiedKFold(n_splits=3)  #there's also stratified shuffle kfold!
cross_val_score(model, X_train, y_train, cv=sk_cv) 

/Users/chaklam/DSAI/Environments/teaching_env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


array([0.30962551, 0.5635614 , 0.59665989])

Another strategy is **Group KFold**:

Very useful if you don't want the same group in both training and validation set.

<img width="400" src = "figures/groupkfold.png">

In [14]:
from sklearn.model_selection import GroupKFold

gkf = GroupKFold(n_splits=5)  #there's also group shuffle kfold!

#we have to specify the group
#let's specify, just for the sake
groups = np.random.randint(0, 5, size=y_train.shape[0])
print(groups.shape)
#print(groups)

cross_val_score(model, X_train, y_train, cv=gkf, groups=groups) 

(309,)


array([0.53971909, 0.44107877, 0.52276067, 0.47754004, 0.4587158 ])

For more details, read https://scikit-learn.org/stable/modules/cross_validation.html#cross-validation

Note: **one big reminder is that cross-validation is for finding optimal hyperparameters/models, you still need to evaluate with final test set**

## Double/Nested Cross-validation

Recall the two problems we have:

1. What if I want to check which hyperparameter is good?  How to check when I should NEVER touch test set?

2. What if somehow I got lucky with my split and my training set is very good, and my test set is also very good, just **by chance*?

Actually, we solved number 1 only!

How about number 2?  Because we may be lucky with our testing set!

**Idea: put another loop when we initally split training and test set, i.e., we now have two loops**

<img width="400" src = "figures/nestedcv.png">

**Then the final performance is simply the average of all outerloop performance, instead of testing the model with final test set, because here, we don't have final test set**

To do nested cross-validation, let's first learn <code>GridSearch</code> which will be needed for doing nested cross-validation quickly.

## Grid Search

Recall that we can compare models/hyperparameters using <code>cross_val_score</code>, right?   But this can be tiring....Scikit-Learn provides automated tools to do this called <code>GridSearchCV</code>:

In [15]:
from sklearn.model_selection import GridSearchCV

param_grid = {'fit_intercept': [True, False],
              'positive': [True, False]}

#GridSearchCV(algorithm, dictionary, cross-validation strategy)
grid = GridSearchCV(model, param_grid, cv=shuffle_cv, refit=True)

grid.fit(X_train, y_train)

GridSearchCV(cv=ShuffleSplit(n_splits=5, random_state=0, test_size=0.3, train_size=None),
             estimator=LinearRegression(),
             param_grid={'fit_intercept': [True, False],
                         'positive': [True, False]})

Now that this is fit, we can ask for the best parameters as follows:

In [16]:
grid.best_params_

{'fit_intercept': True, 'positive': False}

Now we got the new model, we can test it on the final final test set.

In [17]:
y_hat = grid.predict(X_test)  #note that here i can use grid right away, because i specify refit=True
mean_squared_error(y_test, y_hat)

3180.1621027594665

**Please note that there is also other form of gridsearchcv such as randomized grid search which can be more efficient.**

## Coming back to nested cross-validation

Once we learn about grid search, we can utilize both <code>grid search</code> and <code>cross_val_score</code> to perform nested cross validation like this:

In [18]:
from sklearn.model_selection import KFold

#specify the inner cv and outer cv
inner_cv = KFold(n_splits=4, shuffle=True, random_state=1)
outer_cv = KFold(n_splits=4, shuffle=True, random_state=1)

#inner loop
inner_model = GridSearchCV(model, param_grid=param_grid, cv=inner_cv)

#outer loop
nested_score = cross_val_score(inner_model, X, y, scoring='neg_mean_squared_error', cv=outer_cv)
                              
nested_score #higher mean better....(sklearn wants to keep this convention)

#see this ==> https://scikit-learn.org/stable/modules/model_evaluation.html#common-cases-predefined-values

array([-2903.10000132, -3315.33400852, -3144.27434507, -3045.8808507 ])

Now you just average them, and this is your very robust estimates of the model performance.

In [19]:
nested_score.mean()

-3102.1473014039575

There are two big problems of nested cross-validation:
    
1. It is time consuming and resource hungry.
2. You no longer know what hyperparameters or best models....because in the inner loop, the model varies....**so yes, nested cross-validation do not give you a final model!! XD**

**So how to use nested cross-validation**

1. First, use nested cross-validation to look for **model instability**.  If there is a lot of instability, you want to **skip the model or change the search space**.  

2. Once you got a model that is very stable, run a typical (simple, no nested) cross-validation to find the best version of that model, so you can deploy.
    - you can either train (1) on the entire dataset (if you are super sure), or (2) training set (preferable).

**It takes too much time!!!**

1. Make the outer loop smaller OR
2. Don't use it
3. Implement by yourself, and putting breaks to save progress

# Other types of regression

Linear regression is the most basic algorithm.  There are many mores.  Today, we shall briefly talked about other types, for the sake of completeness.   Then we shall revisit the diabetes dataset, and compare different regression algorithms.

## Polynomial Regression

Limitation of simple linear regression comes when we have non-linear data.  We can simply use polynomial regression.  For example, a degree-1 polynomial fits a straight line to the data like this: 

$$y = ax + b$$  

A degree-3 polynomial fits a cubic curve to the data 

$$y = ax^3 + bx^2 + cx + d$$

In scikit learn, we can implement this using a polynomial preprocessor which translate data into its polynomials.

For example, if our x is 

<code>x = np.array([1, 2, 3, 4, 5])</code>

If we perform polynomial transformation like this:

<code>poly_X = PolynomialFeatures(degree = 3).fit_transform(X)</code>
    
X2 will look like this:

<code>[[ 1, 1, 1]
 [ 2, 4, 8]
 [ 3, 9, 27]
 [ 4, 16, 64]
 [ 5, 25, 125]]</code>
 
 Now our new feature_engineered X has one column representing x, second column representing $x^2$, and third column representing $x^3$.  Now the y becomes 
 
 $$ y = ax^3 + bx^2 + cx $$ 
 
Now let's look at some example:

In [ ]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#let's try to fit the model using 1, 3, 5 degrees....
for ix, deg in enumerate([1, 3, 5]):
    print("===Performing polynomial regression with deg: ", deg, "======")
    model = make_pipeline(PolynomialFeatures(deg), LinearRegression())
    model.fit(X_train, y_train)
    y_hat = model.predict(X_test)
    
    #print("Coeff: ", model.named_steps['linearregression'].coef_)
    
    #$(1/n)sigma(y - f(x))^2) where SSE = sigma(y-f(x))^2
    print(f"MSE = {mean_squared_error(y_test, y_hat):.2f}")
    
    #measures goodness of fit
    #1 - SSE/TSS  where TSS = sigma(y-ymean)^2
    #r^2 can be negative, when fit without an intercept
    #We ALMOST never fit without the intercept unless
    #you are sure your data comes through the origin (0, 0), e.g., height, width, but NOT house value!
    #r^2 upper bound is 1, lower bound can be anything
    print(f"r^2 = {r2_score(y_test, y_hat):.3f}")
    
    #calculate adjusted rsquare
    #take IV into consideration, to balance out possible overfitting
    #increases only if new predictor (x) enhances the model
    n, p = X.shape[0], X.shape[1]
    adjusted_rsqrt = 1-(1-r2_score(y_test, y_hat))*(n-1)/(n-p-1)
    print(f"adjusted $r^2$ = {adjusted_rsqrt:.3f}")

===Performing polynomial regression with deg:  1 ======
MSE = 2723.98
r^2 = 0.488
adjusted $r^2$ = 0.476
===Performing polynomial regression with deg:  3 ======
MSE = 1447967.71
r^2 = -271.051
adjusted $r^2$ = -277.363
===Performing polynomial regression with deg:  5 ======
MSE = 1010991.62
r^2 = -188.950
adjusted $r^2$ = -193.357


## Polynomial Regression + Grid Search

Let's apply grid search with polynomial regression

Note: once again, we avoid doing nested cross-validation to save time...but it's recommended.  It helps you check whether the model or the search space really gives stable and generalized results.

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {'polynomialfeatures__degree': np.arange(1, 10),
              'linearregression__fit_intercept': [True, False]}

model = make_pipeline(PolynomialFeatures(), LinearRegression())

grid = GridSearchCV(model, param_grid, cv=3)

grid.fit(X_train, y_train)

print("Best params: ", grid.best_params_)

y_hat = grid.predict(X_test)

Best params:  {'linearregression__fit_intercept': False, 'polynomialfeatures__degree': 1}


In [ ]:
print(f"MSE = {mean_squared_error(y_test, y_hat):.2f}")
print(f"r^2 = {r2_score(y_test, y_hat):.3f}")
n, p = X.shape[0], X.shape[1]
adjusted_rsqrt = 1-(1-r2_score(y_test, y_hat))*(n-1)/(n-p-1)
print(f"adjusted $r^2$ = {adjusted_rsqrt:.3f}")

MSE = 2723.98
r^2 = 0.488
adjusted $r^2$ = 0.476


## Regularization

Regularization is a technique to alleviate overfitting problem by imposing some penalty to the loss function.

### 1. Ridge regression ($L_2$ regularization)

Perhaps the most common form of regularization is known as *ridge regression* or $L_2$ *regularization*, sometimes also called *Tikhonov regularization*. This proceeds by penalizing the sum of squares (2-norms) of the model coefficients; in this case, the penalty on the model fit would be 

$$ J(\theta) =  \frac{1}{2}\sum_{i=1}^m(h_\theta(x^{(i)}) - y^{(i)})^2 + \lambda\sum_{j=1}^n \boldsymbol{\theta}_j^2$$

where $\alpha$ is a free parameter that controls the strength of the penalty.
This type of penalized model is built into Scikit-Learn with the ``Ridge`` estimator:

In [ ]:
from sklearn.linear_model import Ridge
params_Ridge = {'polynomialfeatures__degree': np.arange(1, 10),
                'ridge__alpha': np.logspace(-1, -4, 10)}

##I put normalize=True to reach convergence faster, since it is giving me warnings...as my x value have wide range
model = make_pipeline(PolynomialFeatures(), Ridge(normalize=True))   

### 2. Lasso regression ($L_1$ regularization)

Another very common type of regularization is known as lasso, and involves penalizing the sum of absolute values (1-norms) of regression coefficients:

$$ J(\theta) = \frac{1}{2}\sum_{i=1}^m(h_\theta(x^{(i)}) - y^{(i)})^2+ \lambda\sum_{j=1}^n |\theta_j|$$

Though this is conceptually very similar to ridge regression, the results can differ surprisingly: for example, due to geometric reasons lasso regression tends to favor *sparse models* where possible: that is, it preferentially sets model coefficients to exactly zero.

We can see this behavior in duplicating the ridge regression figure, but using L1-normalized coefficients:

In [ ]:
from sklearn.linear_model import Lasso
params_Lasso = {'polynomialfeatures__degree': np.arange(1, 10),
                'lasso__alpha': np.logspace(-1, -4, 10)}

#put max_iter since it needs more time to reach convergence
model = make_pipeline(PolynomialFeatures(), 
                      Lasso(normalize=True, tol=0.01))

### 3. Elastic net 

Linear regression with combined L1 and L2 regularizer

$$
J(\theta) = \frac{1}{2}\sum_{i=1}^m(h_\theta(x^{(i)}) - y^{(i)})^2 + \alpha \sum_{j=1}^n |\theta_k| + (1 - \alpha) \sum_{k=1}^n \theta_j^2
$$



In [ ]:
from sklearn.linear_model import ElasticNet
#i set tol to be low since it is eating my pc....
model = make_pipeline(PolynomialFeatures(), 
                      ElasticNet(normalize=True))

#note that sklearn has two parameters, alpha and l1_ratio, for the complete equation, refer to the doc
params_Elasticnet = {'polynomialfeatures__degree': np.arange(1, 10),
                'elasticnet__alpha': np.logspace(-1, -4, 10),
                "elasticnet__l1_ratio": np.linspace(0, 1, 5)}

### Ridge or Lasso or Elastic net??

Regularization should be ALMOST ALWAYS used, since these techniques reduces overfitting.

How to choose is a little bit difficult. It is easier to understand the assumptions behind.
1.  Ridge assumes that coefficients are normally distributed.   **Thus, if you don't want any feature to dominate too much, use Ridge.**
2. Lasso assumes that coefficients are Laplace distributed (in layman sense, it mean some predictors are very useful while some are completely irrelevant).   Here, Lasso has the ability to shrink coefficient to zero thus eliminate predictors that are not useful to the output, thus automatic feature selection.  **In simple words, if you have only very few predictors with medium/large effect, use Lasso.**
3.  Elastic basically is a compromise between the two, and thus take huge computation time to reach that compromise.  **If you have the resource to spare, you can use Elastic net**


### 4. ElasticNet + Stochastic Gradient Descent

Sklearn provides ElasticNet along with stochastic gradient descent, and they called <code>SGDRegressor()</code>.

In [ ]:
from sklearn.linear_model import SGDRegressor

model = make_pipeline(PolynomialFeatures(), 
                      SGDRegressor())

params_SGD = {'polynomialfeatures__degree': np.arange(1, 10),
                'sgdregressor__alpha': np.logspace(-1, -4, 10),
                'sgdregressor__penalty': ['l2', 'l1', 'elasticnet'],
                 'sgdregressor__l1_ratio': np.linspace(0, 1, 5),
              'sgdregressor__learning_rate': ['constant', 'optimal',
                                             'invscaling', 'adaptive']}

### Many more....

There are just too many to mention.  It may be nice to read here: https://scikit-learn.org/stable/modules/classes.html#module-sklearn.linear_model.   Sklearn documentation usually writes very good manual when to use which algorithm.  